## Imports and Lib Installs

In [ ]:
!pip install remotezip tqdm opencv-python einops

  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 2.1 MB/s eta 0:00:00
  Created wheel for remotezip: filename=remotezip-0.12.1-py3-none-any.whl size=7933 sha256=822754e4c0a031e663c7a0d875a0a6bf7a1bb1bba4309e97beb0e9af6b258fdc
  Stored in directory: /root/.cache/pip/wheels/fc/76/04/beed1a6df4eb7430ee13c3900746edd517e5e597298d1f73f3
Successfully built remotezip


In [ ]:
!pip install seaborn
!pip install keras
!pip install remotezip
!pip install collection
!pip install picklable-itertools
!pip install pathlib
!pip install random2
!pip install tensorflow
!pip install remotezip tqdm opencv-python einops
!pip install -U statsmodels
!pip install remotezip tqdm opencv-python==4.5.2.52 opencv-python-headless==4.5.2.52 tf-models-official

  Preparing metadata (setup.py) ... done
  Created wheel for collection: filename=collection-0.1.6-py3-none-any.whl size=5098 sha256=92c14395f9889dfb3ab070cb05d63b86e9b018513450830806cdc27901bbb20c
  Stored in directory: /root/.cache/pip/wheels/a5/70/eb/1d28795e9384ab3b9be6359bdde9e1652f6e7dab9d26844f70
Successfully built collection
  Preparing metadata (setup.py) ... done
  Created wheel for picklable-itertools: filename=picklable_itertools-0.1.1-py3-none-any.whl size=15571 sha256=5af462a5c531c4b29d03ecf1390828c76d1c07df7a658dc303d95418c8a2463f
  Stored in directory: /root/.cache/pip/wheels/58/19/34/8fc5b4c7d645b73b2e61f5b48699cefda12a903666e5170b84
Successfully built picklable-itertools
  Preparing metadata (setup.py) ... done
  Created wheel for random2: filename=random2-1.0.1-py3-none-any.whl size=12042 sha256=6bd002f681fd2379c19f93f06ef820ce040d1ca587cbd91294d84e1111ebf2d5
  Stored in directory: /root/.cache/pip/wheels/61/1f/84/8713326a151c1638e7a00202e4074b46e839d22b7d22f8400f
Su

In [ ]:
!pip install tf-models-official

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 28.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 18.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.9/118.9 kB 5.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 69.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 4.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 591.0/591.0 kB 52.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 241.2/241.2 kB 29.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 89.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 62.6 MB/s eta 0:00:00
  Created wheel for pyyaml: filename=PyYAML-5.4.1-cp310-cp310-linux_x86_64.whl size=45658 sha256=5397e

In [ ]:
!pip install remotezip tqdm opencv-python
!pip install -q git+https://github.com/tensorflow/docs

  Preparing metadata (setup.py) ... done


In [ ]:
import tqdm
import random
import pathlib
import itertools
import collections

import cv2
import numpy as np
import remotezip as rz
import seaborn as sns
import matplotlib.pyplot as plt

import keras
import tensorflow as tf
import tensorflow_hub as hub
from tensorflow.keras import layers
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import SparseCategoricalCrossentropy

# Import the MoViNet model from TensorFlow Models (tf-models-official) for the MoViNet model
from official.projects.movinet.modeling import movinet
from official.projects.movinet.modeling import movinet_model

# Video Download

In [ ]:
URL = 'https://storage.googleapis.com/29-06-fly-project/Action_v6.zip'

In [ ]:
def list_files_from_zip_url(zip_url):
  """ List the files in each class of the dataset given a URL with the zip file.

    Args:
      zip_url: A URL from which the files can be extracted from.

    Returns:
      List of files in each of the classes.
  """
  files = []
  with rz.RemoteZip(zip_url) as zip:
    for zip_info in zip.infolist():
      if zip_info.filename[0:3] != "__M":
        files.append(zip_info.filename)
  return files

In [ ]:
files = list_files_from_zip_url(URL)
files = [f for f in files if f.endswith('.avi')]
(files)

['Action_v6/v_Grooming_g01_c326.avi',
 'Action_v6/v_Pumping_g01_c119.avi',
 'Action_v6/v_Grooming_g01_c332.avi',
 'Action_v6/v_Pumping_g01_c125.avi',
 'Action_v6/v_Pumping_g01_c8.avi',
 'Action_v6/v_Pumping_g01_c131.avi',
 'Action_v6/v_Feeding_g01_c249.avi',
 'Action_v6/v_Feeding_g01_c261.avi',
 'Action_v6/v_Feeding_g01_c275.avi',
 'Action_v6/v_Grooming_g01_c124.avi',
 'Action_v6/v_Grooming_g01_c130.avi',
 'Action_v6/v_Pumping_g01_c327.avi',
 'Action_v6/v_Grooming_g01_c118.avi',
 'Action_v6/v_Grooming_g01_c36.avi',
 'Action_v6/v_Grooming_g01_c22.avi',
 'Action_v6/v_Pumping_g01_c333.avi',
 'Action_v6/v_Feeding_g01_c329.avi',
 'Action_v6/v_Feeding_g01_c315.avi',
 'Action_v6/v_Pumping_g01_c290.avi',
 'Action_v6/v_Feeding_g01_c96.avi',
 'Action_v6/v_Feeding_g01_c82.avi',
 'Action_v6/v_Feeding_g01_c301.avi',
 'Action_v6/v_Pumping_g01_c284.avi',
 'Action_v6/v_Feeding_g01_c69.avi',
 'Action_v6/v_Pumping_g01_c253.avi',
 'Action_v6/v_Feeding_g01_c55.avi',
 'Action_v6/v_Feeding_g01_c41.avi',
 'A

In [ ]:
def get_class(fname):
  """ Retrieve the name of the class given a filename.

    Args:
      fname: Name of the file in the UCF101 dataset.

    Returns:
      Class that the file belongs to.
  """
  return fname.split('_')[-3]
get_class(files[10])

'Grooming'

In [ ]:
def get_files_per_class(files):
  """ Retrieve the files that belong to each class.

    Args:
      files: List of files in the dataset.

    Returns:
      Dictionary of class names (key) and files (values).
  """
  files_for_class = collections.defaultdict(list)
  for fname in files:
    class_name = get_class(fname)
    files_for_class[class_name].append(fname)
  return files_for_class
get_files_per_class(files)

defaultdict(list,
            {'Grooming': ['Action_v6/v_Grooming_g01_c326.avi',
              'Action_v6/v_Grooming_g01_c332.avi',
              'Action_v6/v_Grooming_g01_c124.avi',
              'Action_v6/v_Grooming_g01_c130.avi',
              'Action_v6/v_Grooming_g01_c118.avi',
              'Action_v6/v_Grooming_g01_c36.avi',
              'Action_v6/v_Grooming_g01_c22.avi',
              'Action_v6/v_Grooming_g01_c291.avi',
              'Action_v6/v_Grooming_g01_c285.avi',
              'Action_v6/v_Grooming_g01_c252.avi',
              'Action_v6/v_Grooming_g01_c246.avi',
              'Action_v6/v_Grooming_g01_c247.avi',
              'Action_v6/v_Grooming_g01_c253.avi',
              'Action_v6/v_Grooming_g01_c284.avi',
              'Action_v6/v_Grooming_g01_c290.avi',
              'Action_v6/v_Grooming_g01_c23.avi',
              'Action_v6/v_Grooming_g01_c119.avi',
              'Action_v6/v_Grooming_g01_c37.avi',
              'Action_v6/v_Grooming_g01_c131.avi',
     

In [ ]:
NUM_CLASSES = 3
FILES_PER_CLASS = 412
files_for_class = get_files_per_class(files)
classes = list(files_for_class.keys())

In [ ]:
print('Num classes:', len(classes))
print('Num videos for class[0]:', len(files_for_class[classes[2]]))

Num classes: 3
Num videos for class[0]: 412


In [ ]:
def select_subset_of_classes(files_for_class, classes, files_per_class):
  """ Create a dictionary with the class name and a subset of the files in that class.

    Args:
      files_for_class: Dictionary of class names (key) and files (values).
      classes: List of classes.
      files_per_class: Number of files per class of interest.

    Returns:
      Dictionary with class as key and list of specified number of video files in that class.
  """
  files_subset = dict()

  for class_name in classes:
    class_files = files_for_class[class_name]
    files_subset[class_name] = class_files[:files_per_class]

  return files_subset

In [ ]:
files_subset = select_subset_of_classes(files_for_class, classes[:NUM_CLASSES], FILES_PER_CLASS)
list(files_subset.keys())

['Grooming', 'Pumping', 'Feeding']

In [ ]:
def download_from_zip(zip_url, to_dir, file_names):
  """ Download the contents of the zip file from the zip URL.

    Args:
      zip_url: A URL with a zip file containing data.
      to_dir: A directory to download data to.
      file_names: Names of files to download.
  """
  with rz.RemoteZip(zip_url) as zip:
    for fn in tqdm.tqdm(file_names):
      class_name = get_class(fn)
      zip.extract(fn, str(to_dir / class_name))
      unzipped_file = to_dir / class_name / fn

      fn = pathlib.Path(fn).parts[-1]
      output_file = to_dir / class_name / fn
      unzipped_file.rename(output_file)

In [ ]:
def split_class_lists(files_for_class, count):
  """ Returns the list of files belonging to a subset of data as well as the remainder of
    files that need to be downloaded.

    Args:
      files_for_class: Files belonging to a particular class of data.
      count: Number of files to download.

    Returns:
      Files belonging to the subset of data and dictionary of the remainder of files that need to be downloaded.
  """
  split_files = []
  remainder = {}
  for cls in files_for_class:
    split_files.extend(files_for_class[cls][:count])
    remainder[cls] = files_for_class[cls][count:]
  return split_files, remainder

In [ ]:
def download_ufc_101_subset(zip_url, num_classes, splits, download_dir):
  """ Download a subset of the UFC101 dataset and split them into various parts, such as
    training, validation, and test.

    Args:
      zip_url: A URL with a ZIP file with the data.
      num_classes: Number of labels.
      splits: Dictionary specifying the training, validation, test, etc. (key) division of data
              (value is number of files per split).
      download_dir: Directory to download data to.

    Return:
      Mapping of the directories containing the subsections of data.
  """
  files = list_files_from_zip_url(zip_url)
  files.remove(files[0])
  counter=0
  print(len(files))

  files_for_class = get_files_per_class(files)
  print(len(files_for_class['Pumping']))

  classes = list(files_for_class.keys())[:num_classes]
  for cls in classes:
    random.shuffle(files_for_class[cls])

  # Only use the number of classes you want in the dictionary
  files_for_class = {x: files_for_class[x] for x in classes}
  print(files_for_class)
  print(len(files_for_class['Pumping']))

  dirs = {}

  for split_name, split_count in splits.items():
     print(split_name, ":")
     split_dir = download_dir / split_name
     split_files, files_for_class = split_class_lists(files_for_class, split_count)

     print(split_name, len(split_files))
     download_from_zip(zip_url, split_dir, split_files)
     dirs[split_name] = split_dir

  return dirs

# Download

In [ ]:
download_dir = pathlib.Path('./Action_subset/')
subset_paths = download_ufc_101_subset(URL,
                                       num_classes = 3,
                                       splits = {"train": 247, "test": 165},
                                       download_dir = download_dir)

1236
412
{'Grooming': ['Action_v6/v_Grooming_g01_c401.avi', 'Action_v6/v_Grooming_g01_c183.avi', 'Action_v6/v_Grooming_g01_c140.avi', 'Action_v6/v_Grooming_g01_c307.avi', 'Action_v6/v_Grooming_g01_c345.avi', 'Action_v6/v_Grooming_g01_c236.avi', 'Action_v6/v_Grooming_g01_c370.avi', 'Action_v6/v_Grooming_g01_c387.avi', 'Action_v6/v_Grooming_g01_c134.avi', 'Action_v6/v_Grooming_g01_c173.avi', 'Action_v6/v_Grooming_g01_c322.avi', 'Action_v6/v_Grooming_g01_c277.avi', 'Action_v6/v_Grooming_g01_c90.avi', 'Action_v6/v_Grooming_g01_c338.avi', 'Action_v6/v_Grooming_g01_c206.avi', 'Action_v6/v_Grooming_g01_c211.avi', 'Action_v6/v_Grooming_g01_c365.avi', 'Action_v6/v_Grooming_g01_c281.avi', 'Action_v6/v_Grooming_g01_c78.avi', 'Action_v6/v_Grooming_g01_c375.avi', 'Action_v6/v_Grooming_g01_c403.avi', 'Action_v6/v_Grooming_g01_c327.avi', 'Action_v6/v_Grooming_g01_c113.avi', 'Action_v6/v_Grooming_g01_c88.avi', 'Action_v6/v_Grooming_g01_c93.avi', 'Action_v6/v_Grooming_g01_c111.avi', 'Action_v6/v_Groomi

100%|██████████| 741/741 [01:57<00:00,  6.30it/s]


test :
test 495


100%|██████████| 495/495 [01:18<00:00,  6.29it/s]


# Frames

In [ ]:
def format_frames(frame, output_size):
  """
    Pad and resize an image from a video.

    Args:
      frame: Image that needs to resized and padded.
      output_size: Pixel size of the output frame image.

    Return:
      Formatted frame with padding of specified output size.
  """
  frame = tf.image.convert_image_dtype(frame, tf.float32)
  frame = tf.image.resize_with_pad(frame, *output_size)
  return frame

def frames_from_video_file(video_path, n_frames, output_size = (224,224), frame_step = 15):
  """
    Creates frames from each video file present for each category.

    Args:
      video_path: File path to the video.
      n_frames: Number of frames to be created per video file.
      output_size: Pixel size of the output frame image.

    Return:
      An NumPy array of frames in the shape of (n_frames, height, width, channels).
  """
  # Read each video frame by frame
  result = []
  src = cv2.VideoCapture(str(video_path))

  video_length = src.get(cv2.CAP_PROP_FRAME_COUNT)

  need_length = 1 + (n_frames - 1) * frame_step

  if need_length > video_length:
    start = 0
  else:
    max_start = video_length - need_length
    start = random.randint(0, max_start + 1)

  src.set(cv2.CAP_PROP_POS_FRAMES, start)
  # ret is a boolean indicating whether read was successful, frame is the image itself
  ret, frame = src.read()
  result.append(format_frames(frame, output_size))

  for _ in range(n_frames - 1):
    for _ in range(frame_step):
      ret, frame = src.read()
    if ret:
      frame = format_frames(frame, output_size)
      result.append(frame)
    else:
      result.append(np.zeros_like(result[0]))
  src.release()
  result = np.array(result)[..., [2, 1, 0]]

  return result

class FrameGenerator:
  def __init__(self, path, n_frames, training = False):
    """ Returns a set of frames with their associated label.

      Args:
        path: Video file paths.
        n_frames: Number of frames.
        training: Boolean to determine if training dataset is being created.
    """
    self.path = path
    self.n_frames = n_frames
    self.training = training
    self.class_names = sorted(set(p.name for p in self.path.iterdir() if p.is_dir()))
    self.class_ids_for_name = dict((name, idx) for idx, name in enumerate(self.class_names))

  def get_files_and_class_names(self):
    video_paths = list(self.path.glob('*/*.avi'))
    classes = [p.parent.name for p in video_paths]
    return video_paths, classes

  def __call__(self):
    video_paths, classes = self.get_files_and_class_names()

    pairs = list(zip(video_paths, classes))

    if self.training:
      random.shuffle(pairs)

    for path, name in pairs:
      video_frames = frames_from_video_file(path, self.n_frames)
      label = self.class_ids_for_name[name] # Encode labels
      yield video_frames, label

In [ ]:
fg = FrameGenerator(subset_paths['train'], 10, training=True)

frames, label = next(fg())

print(f"Shape: {frames.shape}")
print(f"Label: {label}")

Shape: (10, 224, 224, 3)
Label: 0


# Transfer Learning

In [ ]:
batch_size = 8
num_frames = 8

output_signature = (tf.TensorSpec(shape = (None, None, None, 3), dtype = tf.float32),
                    tf.TensorSpec(shape = (), dtype = tf.int16))

train_ds = tf.data.Dataset.from_generator(FrameGenerator(subset_paths['train'], num_frames, training = True),
                                          output_signature = output_signature)
train_ds = train_ds.batch(batch_size)

test_ds = tf.data.Dataset.from_generator(FrameGenerator(subset_paths['test'], num_frames),
                                         output_signature = output_signature)
test_ds = test_ds.batch(batch_size)

In [ ]:
for frames, labels in train_ds.take(10):
  print(labels)

tf.Tensor([0 1 2 0 2 0 1 2], shape=(8,), dtype=int16)
tf.Tensor([2 2 2 2 1 1 1 1], shape=(8,), dtype=int16)
tf.Tensor([1 1 0 2 1 1 2 1], shape=(8,), dtype=int16)
tf.Tensor([0 0 0 2 1 2 2 0], shape=(8,), dtype=int16)
tf.Tensor([2 2 1 1 0 2 1 1], shape=(8,), dtype=int16)
tf.Tensor([0 0 0 1 0 2 0 2], shape=(8,), dtype=int16)
tf.Tensor([2 1 0 0 2 0 2 1], shape=(8,), dtype=int16)
tf.Tensor([2 2 0 1 2 2 2 1], shape=(8,), dtype=int16)
tf.Tensor([2 2 0 2 0 2 2 0], shape=(8,), dtype=int16)
tf.Tensor([2 0 1 0 0 2 1 2], shape=(8,), dtype=int16)


In [ ]:
print(f"Shape: {frames.shape}")
print(f"Label: {labels.shape}")

Shape: (8, 8, 224, 224, 3)
Label: (8,)


In [ ]:
gru = layers.GRU(units=4, return_sequences=True, return_state=True)

inputs = tf.random.normal(shape=[1, 10, 8]) # (batch, sequence, channels)

result, state = gru(inputs) # Run it all at once

In [ ]:
first_half, state = gru(inputs[:, :5, :])   # run the first half, and capture the state
second_half, _ = gru(inputs[:,5:, :], initial_state=state)  # Use the state to continue where you left off.

print(np.allclose(result[:, :5,:], first_half))
print(np.allclose(result[:, 5:,:], second_half))

True
True


In [ ]:
model_id = 'a0'
resolution = 224

tf.keras.backend.clear_session()

backbone = movinet.Movinet(model_id=model_id)
backbone.trainable = True

# Set num_classes=600 to load the pre-trained weights from the original model
num_classes = 600  # Replace 10 with the actual number of action classes in your dataset
model = movinet_model.MovinetClassifier(backbone=backbone, num_classes=num_classes)
model.build([None, None, None, None, 3])

# Load pre-trained weights
!wget https://storage.googleapis.com/tf_model_garden/vision/movinet/movinet_a0_base.tar.gz -O movinet_a0_base.tar.gz -q
!tar -xvf movinet_a0_base.tar.gz

checkpoint_dir = f'movinet_{model_id}_base'
checkpoint_path = tf.train.latest_checkpoint(checkpoint_dir)
checkpoint = tf.train.Checkpoint(model=model)
status = checkpoint.restore(checkpoint_path)
status.assert_existing_objects_matched()

movinet_a0_base/
movinet_a0_base/checkpoint
movinet_a0_base/ckpt-1.data-00000-of-00001
movinet_a0_base/ckpt-1.index


In [ ]:
def build_classifier(batch_size, num_frames, resolution, backbone, num_classes):
  """Builds a classifier on top of a backbone model."""
  model = movinet_model.MovinetClassifier(
      backbone=backbone,
      num_classes=num_classes)
  model.build([batch_size, num_frames, resolution, resolution, 3])

  return model

In [ ]:
model = build_classifier(batch_size, num_frames, resolution, backbone, 3)

In [ ]:
num_epochs = 4

loss_obj = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

optimizer = tf.keras.optimizers.Adam(learning_rate = 0.001)

model.compile(loss=loss_obj, optimizer=optimizer, metrics=['accuracy'])

In [ ]:
results = model.fit(train_ds,
                    validation_data=test_ds,
                    epochs=num_epochs,
                    validation_freq=1,
                    verbose=1)

Epoch 1/4
93/93 [==============================] - 529s 5s/step - loss: 0.8623 - accuracy: 0.7679 - val_loss: 0.7181 - val_accuracy: 0.7960
Epoch 2/4
93/93 [==============================] - 411s 4s/step - loss: 0.3652 - accuracy: 0.8880 - val_loss: 0.3610 - val_accuracy: 0.8525
Epoch 3/4
93/93 [==============================] - 405s 4s/step - loss: 0.3879 - accuracy: 0.8718 - val_loss: 0.4004 - val_accuracy: 0.9313
Epoch 4/4
93/93 [==============================] - 400s 4s/step - loss: 0.3210 - accuracy: 0.9055 - val_loss: 0.2648 - val_accuracy: 0.9434


In [ ]:
model.evaluate(test_ds, return_dict=True)

In [ ]:
while True:pass

# Streaming Model - Pt.2 Alternative

In [ ]:
model_id = 'a2'
mode = 'stream'
version = '3'
hub_url = f'https://tfhub.dev/tensorflow/movinet/{model_id}/{mode}/kinetics-600/classification/{version}'
model = hub.load(hub_url)

In [ ]:
num_epochs = 2

loss_obj = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

optimizer = tf.keras.optimizers.Adam(learning_rate = 0.001)

model.compile(loss=loss_obj, optimizer=optimizer, metrics=['accuracy'])

AttributeError: ignored